name: Gemini AI Integration


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  gemini-ai-task:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install Gemini CLI
      run: |
          curl -sSL https://sdk.cloud.google.com | bash
                    source ~/.bashrc
                              gcloud components install beta
                                        pip install google-generativeai
    - name: Configure Gemini CLI
          python -c "import google.generativeai as genai; genai.configure(api_key='${{ secrets.GEMINI_API_KEY }}'); model = genai.GenerativeModel('gemini-pro'); response = model.generate_content('Hello from GitHub Actions!'); print(response.text)"          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV
                    python -c "import google.generativeai as genai; print('Gemini API configured successfully')"          python -c "import google.generativeai as genai; print('Gemini API configured successfully')"echo '{"apiKey": "${{ secrets.GEMINI_API_KEY }}"}'> ~/.gemini/settings.json
    
    - name: Test Gemini AI
      run: |
        echo 'Hello from GitHub Actions! Please confirm this workflow is working.' | gemini
    
    - name: Generate AI Summary
      run: |
        echo 'Please provide a brief summary of what this GitHub Actions workflow does.' | gemini
